config/routes.rb
Budzogan::Application.routes.draw do
  authenticated :user do
    root 'static_pages#home', as: :authenticated
  end

  root 'static_pages#landing'

  devise_for :users, path: '', path_names: { sign_up: :join, sign_in: :login, sign_out: :logout }

  resources :sentences, only: [:create]

  resources :tasks, only: [:index, :edit, :update]

  resources :workgroups

  resources :exercises, only: [:create, :edit, :index] do
    resources :build, controller: 'exercises/build'
  end

  get 'sentences/generate', controller: 'sentences/generate'

  get 'tasks/generate', controller: 'tasks/generate'

  get 'help', to: 'static_pages#help'
end

app/models/task.rb
class Task < ActiveRecord::Base
  STATES = [:new, :in_progress, :solved]

  belongs_to :exercise
  belongs_to :sentence, counter_cache: true
  belongs_to :user

  before_create :initialize_solution

  validates :exercise, presence: true

  scope :started, lambda { where.not(state: 0) }

  def initialize_solution
    teacher_solution = student_solution = "{\"cells\":[]}"
  end

  def initialize_state
    state = STATES.first
  end

  def self.create_and_assign(sentences, assignee, exercise)
    sentences.each do |sentence|
      Task.create(sentence: sentence, user: assignee, exercise: exercise)
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = current_user.tasks.order(created_at: :desc)
    # @tasks.page(params[:page]).per(10)
  end

  def edit
    @task = Task.find(params[:id])
    @sentence = Task.find(params[:id]).sentence.content.split

    @used_words = []
    @used_words = @task.student_solution["cells"].map {|cell| cell["attrs"]["text"]["text"] if cell["type"] == "nlp.Element"} if @task.student_solution
    @used_words.compact!
    @used_words = @used_words.collect(&:split).flatten
  end

  def update
    @task = Task.find(params[:id])

    @task.student_solution = params[:graph].to_json || @task.student_solution

    # TODO weird task state representation
    @task.state = params[:state].to_i || 0

    @task.elapsed_time += params[:time].to_i

    @task.save!

    render nothing: true
  end

  def generate
    @sentences = Sentence.get_bulk(10, current_user)

    # TODO get reasonable exercise value
    Task.create_and_assign(@sentences, current_user, Exercise.first)

    redirect_to tasks_path
  end

  private

  def empty?

  end
end

app/views/tasks/_box_details.html.erb
<div id="box-editing" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <div id="box"></div>
        <div class="row">
          <div class="col-md-3">Vetný člen:</div>
          <div class="col-md-9">
            <select class="form-control" id="sentence-element">
              <option value="subject">Podmet</option>
              <option value="predicate">Prísudok</option>
              <option value="object">Predmet</option>
              <option value="attribute">Prívlastok</option>
            </select>
          </div>
        </div>
        <div class="row">
          <div class="col-md-3">Pád:</div>
          <div class="col-md-9">
            <select class="form-control" id="grammatical-case">
              <option value="1">Nominatív</option>
              <option value="2">Genitív</option>
              <option value="3">Datív</option>
              <option value="4">Akuzatív</option>
              <option value="5">Lokál</option>
              <option value="6">Inštrumentál</option>
            </select>
          </div>
        </div>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Zrušiť</button>
        <button type="button" class="btn btn-primary" id="save-box">Uložiť</button>
      </div>
    </div>
  </div>
</div>

app/views/tasks/_connection_details.html.erb
<div id="connection-editing" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <div id="connection"></div>
        <div class="row">
          <div class="col-md-6">Typ skladu:</div>
          <div class="col-md-6">
            <select class="form-control" id="connection-type">
              <option value="assignative">Priraďovací</option>
              <option value="predicative">Podraďovací</option>
              <option value="determinative">Určovací</option>
            </select>
          </div>
        </div>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Zrušiť</button>
        <button type="button" class="btn btn-primary" id="save-connection">Uložiť</button>
      </div>
    </div>
  </div>
</div>

app/views/tasks/_progress.html.erb
<% if task.state == 0 %>
  <div class="progress">
    <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%"></div>
  </div>
<% elsif task.state == 1 %>
  <div class="progress">
    <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width: 50%"></div>
  </div>
<% else %>
  <div class="progress">
    <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%"></div>
  </div>
<% end %>

app/views/tasks/_properties.html.erb
<h4 id="properties-title" class="text-muted">Vlastnosti</h4>

<div id="level-1-properties" hidden="hidden">
  <h5 id="level-1-title"></h5>
  <input id="level-1-select" type="hidden"/>
</div>

<div id="level-2-properties" hidden="hidden">
  <h5 id="level-2-title"></h5>
  <input id="level-2-select" type="hidden"/>
</div>

<div id="level-3-properties" hidden="hidden">
  <h5 id="level-3-title"></h5>
  <input id="level-3-select" type="hidden"/>
</div>

<button id="save-properties" class="btn btn-default" disabled="disabled">Uložiť vlastnosti</button>

app/views/tasks/edit.html.erb
<div id="edit-task" class="row task-header">
  <div class="col-md-2">
    <%= link_to 'Zoznam úloh', tasks_path, class: 'btn btn-lg btn-block btn-primary', id: 'back' %>
    <%= link_to 'Odovzdať', tasks_path, class: 'btn btn-lg btn-block btn-success', id: 'submit-task' %>
  </div>
  <div class="col-md-10">
    <div class="well">
      <p class="text-muted">Veta na rozbor:</p>
      <p class="analyzed-sentence">
        <% @sentence.each_with_index do |word, index| %>
          <% if @used_words.include? word %>
            <span class="text-draggable disabled" id="text-<%= index %>"><%= word %></span>
          <% else %>
            <span class="text-draggable" id="text-<%= index %>"><%= word %></span>
          <% end %>
        <% end %>
      </p>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-2">
    <div class="well itemized" id="boxes">
      <h4>Vetné členy</h4>
    </div>
    <div class="well itemized" id="lines">
      <h4>Vetné sklady</h4>
      <small>Prisudzovací</small>
      <div class="line-draggable">
        <span id="assignative"></span>
      </div>
      <hr/>
      <small>Priraďovací</small>
      <div class="line-draggable">
        <span id="predicative"></span>
      </div>
      <hr/>
      <small>Určovací</small>
      <div class="line-draggable">
        <span id="determinative"></span>
      </div>
    </div>
  </div>

  <div class="col-md-8">
    <div class="myContainer" id="paper" data-state="<%= @task.state %>" data-value="<%= @task.student_solution.to_json %>"></div>
  </div>

  <div class="col-md-2">
    <div class="well" id="properties">
      <%= render 'properties' %>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <h4 class="text-center">Ak sa tu nevyznáš, <%= link_to 'pozri sem.', help_path, class: 'btn btn-info' %></h4>
  </div>
</div>

<div id="tasks" class="row">
  <div class="col-md-12">
    <% if @tasks.any?  %>
        <div class="col-md-8"><h3 class="pull-left">Urob kompletný rozbor týchto viet.</h3></div>
        <div class="col-md-4"><%= link_to 'Ďalších 10 úloh', tasks_generate_path, class: 'btn btn-lg btn-primary pull-right' %></div>

        <table class="table table-hover table-condensed">
          <thead>
            <tr>
              <th>Stav úlohy</th>
              <th>Veta</th>
            </tr>
          </thead>
          <tbody>
            <% @tasks.each do |task| %>
              <tr>
                <td><%= render 'progress', task: task %></td>
                <td><%= link_to "#{ task.sentence.content }",  edit_task_path(task.id) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
    <% else %>
        <div class="alert alert-warning">
          <p class="text-center">Ešte nemáš vygenerované žiadne úlohy, <%= link_to 'vygeneruj si prvých 10.', tasks_generate_path %></p>
        </div>
    <% end %>
  </div>
</div>

app/views/tasks/solve.html.erb
<div class="row">
  <div class="col-md-offset-3 col-md-9">
    <div class="well">
      <p>
        <% @sentence.each do |word| %>
          <span class="text-draggable"><%= word %></span>
        <% end %>
      </p>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-3">
    <div class="well itemized" id="boxes">
      <h2>Vetné členy</h2>
    </div>
    <div class="well itemized" id="lines">
      <h2>Vetné sklady</h2>
    </div>
  </div>
  <div class="col-md-9 myContainer" id="paper">

  </div>
</div>