config/routes.rb
Budzogan::Application.routes.draw do
  authenticated :user do
    root 'static_pages#home', as: :authenticated
  end

  root 'static_pages#landing'

  devise_for :users, path: '', path_names: { sign_up: :join, sign_in: :login, sign_out: :logout }

  resources :sentences, only: [:create]

  resources :tasks, only: [:index, :edit, :update]

  resources :workgroups

  resources :exercises, only: [:create, :edit, :index] do
    resources :build, controller: 'exercises/build'
  end

  get 'sentences/generate', controller: 'sentences/generate'

  get 'tasks/generate', controller: 'tasks/generate'

  get 'help', to: 'static_pages#help'
end

app/models/sentence.rb
class Sentence < ActiveRecord::Base
  serialize :solution, Hash

  has_and_belongs_to_many :exercises

  has_many :tasks

  scope :starters, lambda{ |bulk_size| order(id: :asc).limit(bulk_size) }
  scope :needed,   lambda{ |ids_list| order(id: :asc).where('tasks_count < 40').where('id not in (?)', ids_list) }

  scope :long,   lambda{ |count| where('length > 10').limit(count) }
  scope :medium, lambda{ |count| where('length > 5').where('length < 11').limit(count) }
  scope :short,  lambda{ |count| where('length < 6').limit(count) }

  before_create :compute_length

  def self.get_bulk(size, assignee)
    tasks_pool = self.needed(invalid_ids_for(assignee))
    sentences = []

    if assignee.tasks.count == 0
      size -= 4
    end

    remaining = size
    bulk_size = size/3

    tasks_pool.long(bulk_size).each { |s| sentences << s }
    remaining -= bulk_size
    tasks_pool.medium(bulk_size).each { |s| sentences << s }
    remaining -= bulk_size
    tasks_pool.short(remaining).each { |s| sentences << s }

    if assignee.tasks.count == 0
      self.starters(4).each { |s| sentences << s }
    end
    
    sentences
  end

  private
  def compute_length
    length = content.split(' ').count
  end

  def self.invalid_ids_for(user)
    list = user.tasks.map(&:sentence_id)

    list.empty? ? [-1] : list
  end
end

app/controllers/sentences_controller.rb
class SentencesController < ApplicationController
  def generate
    @generator = SentenceGenerator::Generator.new
    @sentences = Sentence.where('length < 8').limit(10) # @generator.generate_sentences()
  end

  def create
    @sentence = Sentence.where(sentence_params).first_or_create!
  end

  private

  def sentence_params
    params.require(:sentence).permit(:content, :source)
  end
end

app/views/sentences/_sentences.html.erb
<%= link_to 'Generuj 10 nových viet', sentences_generate_path(length: 6, source: ''), remote: true, class: 'btn btn-default pull-right' %>

<table class="table" id="sentences-table">
  <thead>
    <tr class="active">
      <th>Veta</th>
      <th>Zdroj vety</th>
      <th>Akcie</th>
    </tr>
  </thead>

  <tbody>
    <% @sentences.each do |sentence| %>
      <tr>
        <td sentence-id="<%= sentence.id %>"><%= sentence.content %></td>
        <td><%= sentence.source %></td>
        <td><%= link_to 'Zmaž vetu', '#', class: 'btn btn-danger delete-sentence' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="input-group">
  <input id="sentence-to-add" class="form-control" type="text"/>
  <span class="input-group-btn">
    <%= button_tag 'Pridaj vetu', type: '', class: 'btn btn-success add-sentence' %>
  </span>
</div>