config/routes.rb
Budzogan::Application.routes.draw do
  authenticated :user do
    root 'static_pages#home', as: :authenticated
  end

  root 'static_pages#landing'

  devise_for :users, path: '', path_names: { sign_up: :join, sign_in: :login, sign_out: :logout }

  resources :sentences, only: [:create]

  resources :tasks, only: [:index, :edit, :update]

  resources :workgroups

  resources :exercises, only: [:create, :edit, :index] do
    resources :build, controller: 'exercises/build'
  end

  get 'sentences/generate', controller: 'sentences/generate'

  get 'tasks/generate', controller: 'tasks/generate'

  get 'help', to: 'static_pages#help'
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  STATUSES   = [:new, :setup, :sentences, :assignment, :active]
  LEVELS     = [:easy, :medium, :hard]
  STRATEGIES = [:one_to_one, :every_to_everyone, :custom]

  has_and_belongs_to_many :sentences

  belongs_to :template, class_name: :ExerciseTemplate
  belongs_to :workgroup

  has_many :element_assignments, as: :elementable, dependent: :destroy
  has_many :elements, through: :element_assignments

  has_many :tasks, dependent: :destroy

  with_options if: :active_or_setup? do |exercise|
    exercise.validates :description, format: { with: /[\s\w\<\>\?\.\,\:\;\'\"\{\}\(\)]*/ }, presence: true
    exercise.validates :template_id, numericality: true, presence: true
  end

  with_options if: :active_or_sentences? do |exercise|
    exercise.validates :sentence_length, numericality: { only_integer: true }, allow_blank: true
    exercise.validates :sentence_difficulty, inclusion: { in: LEVELS }, allow_blank: true
  end

  validates :distribution_strategy, presence: true, inclusion: { in: STRATEGIES }, if: :active_or_assignment?

  validates :status, inclusion: { in: STATUSES }, presence: true

  symbolize :status
  symbolize :sentence_difficulty
  symbolize :distribution_strategy

  def active?
    status == :active
  end

  def active_or_setup?
    status.eql?(:setup) || active?
  end

  def active_or_sentences?
    status.eql?(:sentences) || active?
  end

  def active_or_assignment?
    status.eql?(:assignment) || active?
  end

  def sentences_ids
    self.sentences.ids
  end
end

app/views/shared/_elements_checkboxes.html.erb
<div class="col-md-6 elements-checkboxes">
<strong class="group-title"><%= title %></strong>
<%= f.collection_check_boxes(:element_ids, elements, :id, :name) do |b| %>
  <div class="row element">
    <div class="col-xs-1">
      <%= b.check_box(class: 'check_box') %>
    </div>
    <div class="col-xs-11">
      <label class="text-left checkbox-option"><%= b.object.name %></label>
    </div>
  </div>
<% end %>
</div>

app/views/shared/_flash_messages.html.erb
<% if flash.any? %>
  <section id="flash">
    <div class="row">
      <div class="col-md-12">
        <% flash.each do |type, messages| %>
            <% Array.wrap(messages).each do |message| %>
                <div class="alert alert-<%= flash_type_to_class type %> alert-dismissable">
                  <%= message.html_safe %>
                </div>
            <% end %>
        <% end %>
      </div>
    </div>
  </section>
<% end %>

app/views/shared/_form_messages.html.erb
<% if model.errors.any? %>
    <div class="error_messages">
      <% model.errors.full_messages.each do |msg| %>
          <div class="alert alert-danger alert-dismissable">
            <%= msg.html_safe %>
          </div>
      <% end %>
    </div>
<% end %>