config/routes.rb
Budzogan::Application.routes.draw do
  authenticated :user do
    root 'static_pages#home', as: :authenticated
  end

  root 'static_pages#landing'

  devise_for :users, path: '', path_names: { sign_up: :join, sign_in: :login, sign_out: :logout }

  resources :sentences, only: [:create]

  resources :tasks, only: [:index, :edit, :update]

  resources :workgroups

  resources :exercises, only: [:create, :edit, :index] do
    resources :build, controller: 'exercises/build'
  end

  get 'sentences/generate', controller: 'sentences/generate'

  get 'tasks/generate', controller: 'tasks/generate'

  get 'help', to: 'static_pages#help'
end

app/views/layouts/_header.html.erb
<header id="header-navbar" class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
      </button>
      <%= navbar_logo_tag default_title %>
    </div>
    <% if user_signed_in? %>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <%= content_tag :li, link_to(t('task.navigation'), tasks_path) %>
            <%= content_tag :li, link_to('Pomoc', help_path) %>
            <%= content_tag :li, link_to(t('exercise.new.title'), exercises_path, method: :post) if can?(:administrate, Exercise) %>
            <%= content_tag :li, link_to(t('workgroup.navigation'), workgroups_path) if can?(:administrate, Workgroup) %>
          </ul>
        <ul class="nav navbar-nav navbar-right">
          <%= content_tag :li, link_to(current_user.nick, '#') %>
          <%= content_tag :li, link_to(t('user.sign_out'), destroy_user_session_path, method: :delete) %>
        </ul>
    <% else %>
        <ul class="nav navbar-nav navbar-right">
          <%= content_tag :li, link_to(t('user.sign_in'), new_user_session_path) %>
          <% if Configuration.enable.registrations? %>
              <%= content_tag :li, link_to(t('user.sign_up'), new_user_registration_path) %>
          <% end %>
        </ul>
    <% end %>
    </div>
  </div>
</header>

<%= yield :header %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title> <%= default_title %> </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= stylesheet_link_tag 'application', media: :all %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= render 'shared/flash_messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  <%= javascript_include_tag 'application' %>
  </body>
</html>